import type {
  AgentRun,
  CalendarEvent,
  HQNotification,
  Person,
  Task,
} from "./types";

// All seed times are computed relative to "now" so the prototype always
// feels live: countdowns count down, "due today" is actually today.
const now = new Date();

function at(hour: number, min = 0, dayOffset = 0): string {
  const d = new Date(now);
  d.setDate(d.getDate() + dayOffset);
  d.setHours(hour, min, 0, 0);
  return d.toISOString();
}

function minsFromNow(mins: number): string {
  return new Date(now.getTime() + mins * 60000).toISOString();
}

export const PEOPLE: Person[] = [
  {
    id: "omar",
    name: "Omar",
    role: "Founder · Product & Engineering",
    owns: ["Engine", "Pendant firmware", "Fundraise"],
    focus: "Pendant microphone bring-up",
    email: "omar@anticipy.ai",
    phone: "+1 604 ··· 8841",
    reminderPref: "Email + SMS",
    calendarStatus: "In focus block until 11:00",
  },
  {
    id: "ari",
    name: "Ari",
    role: "Software · Engine & Desktop",
    owns: ["Onboarding", "Desktop app", "Agent runs"],
    focus: "Onboarding permission flow fix",
    email: "ari@anticipy.ai",
    phone: "+1 778 ··· 2210",
    reminderPref: "SMS",
    calendarStatus: "Free until 14:00",
  },
  {
    id: "jose",
    name: "Jose",
    role: "Hardware · Manufacturing & Ops",
    owns: ["PCB", "Enclosure", "Manufacturing"],
    focus: "Battery performance test matrix",
    email: "jose@anticipy.ai",
    phone: "+1 236 ··· 5502",
    reminderPref: "Email",
    calendarStatus: "In meeting until 10:30",
  },
];

let taskCounter = 0;
function t(partial: Partial<Task> & { title: string }): Task {
  taskCounter += 1;
  return {
    id: `task-${taskCounter}`,
    outcome: "",
    owner: null,
    agentRunId: null,
    status: "open",
    priority: "normal",
    project: "Company",
    due: null,
    recurrence: "none",
    reminder: null,
    notes: "",
    checklist: [],
    dependsOn: [],
    links: [],
    comments: [],
    activity: [
      { id: `a-${taskCounter}-1`, text: "Task created", at: at(8, 5, -1) },
    ],
    scheduledAt: null,
    proof: null,
    createdAt: at(8, 0, -1),
    order: taskCounter,
    ...partial,
  };
}

export const TASKS: Task[] = [
  t({
    title: "Test the pendant microphone against 60s rolling windows",
    outcome: "Confident yes/no on whether the INMP441 keeps up with rolling capture.",
    owner: "omar",
    status: "in_progress",
    priority: "urgent",
    project: "Hardware",
    due: at(12, 0),
    checklist: [
      { id: "c1", text: "Record 10 windows in quiet room", done: true },
      { id: "c2", text: "Record 10 windows with music playing", done: true },
      { id: "c3", text: "Compare transcripts against reference", done: false },
    ],
    notes: "Use the v2 prototype board. The v1 board has the mic clock issue.",
    comments: [
      { id: "cm1", author: "jose", text: "v2 boards are in the grey bin by the soldering station.", at: at(17, 42, -1) },
    ],
  }),
  t({
    title: "Fix onboarding permission flow on macOS 15",
    outcome: "A new user gets through mic + accessibility permissions without a dead end.",
    owner: "ari",
    agentRunId: "run-1",
    status: "in_progress",
    priority: "urgent",
    project: "Software",
    due: at(17, 0),
    dependsOn: [],
    notes: "TCC prompt ordering changed in macOS 15.2. Repro: fresh user account, run installer.",
  }),
  t({
    title: "Review Alta Manufacturing update on enclosure tooling",
    outcome: "Reply to Alta with a go / no-go on the revised draft angle.",
    owner: "jose",
    status: "open",
    priority: "important",
    project: "Hardware",
    due: at(15, 0),
    links: [{ label: "Alta email thread", href: "#" }],
  }),
  t({
    title: "Prepare 45s product video for the pre-order page",
    outcome: "A cut Omar can approve, focused on the approve-then-act loop.",
    owner: "ari",
    status: "open",
    priority: "normal",
    project: "Growth",
    due: at(10, 0, 2),
    checklist: [
      { id: "c4", text: "Script the three scenes", done: true },
      { id: "c5", text: "Screen-record the Gmail draft flow", done: false },
      { id: "c6", text: "Rough cut", done: false },
    ],
  }),
  t({
    title: "Check battery performance across 8-hour wear test",
    outcome: "Battery curve chart and a pass/fail against the 10-hour target.",
    owner: "jose",
    status: "blocked",
    priority: "important",
    project: "Hardware",
    due: at(9, 0, 1),
    notes: "Blocked: waiting on the new battery specification from Omar before starting the matrix.",
    dependsOn: ["task-9"],
  }),
  t({
    title: "Follow up with Marcus (Foreword Ventures) after Tuesday call",
    outcome: "A short email with the DIL results he asked about, sent by end of day.",
    owner: "omar",
    status: "waiting",
    priority: "important",
    project: "Fundraise",
    due: at(16, 30),
    notes: "Draft is ready in the agent run. Needs Omar's review before sending — external email.",
    agentRunId: "run-3",
  }),
  t({
    title: "Debug agent run #482 — Calendar event created twice",
    outcome: "Root cause identified and a safety binding added so it cannot recur.",
    owner: "ari",
    agentRunId: "run-2",
    status: "in_progress",
    priority: "important",
    project: "Software",
    due: at(18, 0),
  }),
  t({
    title: "Order 5 more v2 prototype boards from JLCPCB",
    outcome: "Order confirmed with DHL Express shipping.",
    owner: "jose",
    status: "done",
    priority: "normal",
    project: "Hardware",
    due: at(17, 0, -1),
    proof: "Order #JL-88412 confirmation, 5 pcs, arrives Thursday.",
    activity: [
      { id: "a-d1", text: "Task created", at: at(9, 0, -2) },
      { id: "a-d2", text: "Jose marked done — order #JL-88412", at: at(16, 20, -1) },
    ],
  }),
  t({
    title: "Write the new battery specification for the wear test",
    outcome: "One page: capacity, discharge profile, cutoff voltage, pass criteria.",
    owner: "omar",
    status: "open",
    priority: "urgent",
    project: "Hardware",
    due: at(14, 0),
    notes: "Jose is blocked on this. Keep it to one page.",
  }),
  t({
    title: "Weekly clean-room deployment test",
    outcome: "Fresh install passes the Done Gate with zero nursing.",
    owner: "ari",
    status: "open",
    priority: "normal",
    project: "Software",
    due: at(11, 0, 4),
    recurrence: "weekly",
  }),
  t({
    title: "Reply to three pre-order support emails",
    outcome: "Inbox at zero for support@.",
    owner: "omar",
    status: "done",
    priority: "normal",
    project: "Company",
    due: at(9, 30, -1),
    proof: "Three replies sent; one refund processed per policy.",
  }),
  t({
    title: "Draft Q1 investor update",
    outcome: "A draft in the shared doc ready for team review Friday.",
    owner: "omar",
    status: "open",
    priority: "later",
    project: "Fundraise",
    due: at(12, 0, 5),
  }),
  t({
    title: "Verify Parakeet ASR latency on M1 Air baseline",
    outcome: "P50/P95 latency numbers recorded for the slowest supported Mac.",
    owner: null,
    agentRunId: "run-4",
    status: "waiting",
    priority: "normal",
    project: "Software",
    due: at(13, 0, 1),
  }),
  t({
    title: "Update BOM with the revised mic gasket part",
    outcome: "BOM row updated with part number and unit cost.",
    owner: "jose",
    status: "cancelled",
    priority: "later",
    project: "Hardware",
    activity: [
      { id: "a-c1", text: "Task created", at: at(10, 0, -3) },
      { id: "a-c2", text: "Cancelled — gasket redesign superseded this", at: at(15, 0, -1) },
    ],
  }),
];

export const AGENT_RUNS: AgentRun[] = [
  {
    id: "run-1",
    taskId: "task-2",
    taskName: "Fix onboarding permission flow on macOS 15",
    agent: "Claude Code",
    requester: "ari",
    startedAt: minsFromNow(-38),
    runtimeMin: 38,
    tokens: 412_000,
    costUsd: 3.12,
    status: "waiting_approval",
    liveStatus: "Waiting for approval",
    budgetUsd: 10,
    timeLimitMin: 90,
    steps: [
      { id: "s1", label: "Read repository", detail: "engine/app/anticipy/onboarding", at: minsFromNow(-37), state: "done", raw: "git clone … && rg 'TCC' engine/ — 14 files matched" },
      { id: "s2", label: "Found relevant files", detail: "3 files govern the permission sequence", at: minsFromNow(-31), state: "done", raw: "onboarding/permissions.py, tcc_seed.sh, desktop/src/setup.rs" },
      { id: "s3", label: "Proposed plan", detail: "Reorder mic prompt before AX prompt; add retry", at: minsFromNow(-26), state: "done" },
      { id: "s4", label: "Changed three files", at: minsFromNow(-14), state: "done", raw: "+84 −22 across 3 files" },
      { id: "s5", label: "Tests passed", detail: "11/11 onboarding tests green", at: minsFromNow(-6), state: "done", raw: "pytest engine/tests/test_onboarding.py — 11 passed in 42.1s" },
      { id: "s6", label: "Waiting for approval to update the onboarding database", at: minsFromNow(-2), state: "active" },
    ],
    question: null,
    approval: {
      action: "Run a migration that adds a `permission_state` column to the onboarding database and backfills 214 rows.",
      reason: "Schema changes are a risky action. Nothing risky happens silently.",
    },
    proof: null,
  },
  {
    id: "run-2",
    taskId: "task-7",
    taskName: "Debug agent run #482 — Calendar event created twice",
    agent: "General AI",
    requester: "ari",
    startedAt: minsFromNow(-12),
    runtimeMin: 12,
    tokens: 96_000,
    costUsd: 0.71,
    status: "working",
    liveStatus: "Reading trajectory logs",
    budgetUsd: 5,
    timeLimitMin: 60,
    steps: [
      { id: "s1", label: "Read trajectory for run #482", at: minsFromNow(-11), state: "done", raw: "state/trajectories/482.jsonl — 1,204 events" },
      { id: "s2", label: "Found double-fire in commitment detector", detail: "Same 60s window processed twice", at: minsFromNow(-4), state: "done" },
      { id: "s3", label: "Verifying against safety bindings", at: minsFromNow(-1), state: "active" },
    ],
    question: null,
    approval: null,
    proof: null,
  },
  {
    id: "run-3",
    taskId: "task-6",
    taskName: "Draft investor follow-up for Marcus",
    agent: "General AI",
    requester: "omar",
    startedAt: minsFromNow(-95),
    runtimeMin: 9,
    tokens: 41_000,
    costUsd: 0.28,
    status: "waiting_approval",
    liveStatus: "Draft ready for review",
    budgetUsd: 2,
    timeLimitMin: 30,
    steps: [
      { id: "s1", label: "Read Tuesday call notes", at: minsFromNow(-94), state: "done" },
      { id: "s2", label: "Pulled DIL results Marcus asked about", detail: "112/116 events handled", at: minsFromNow(-91), state: "done" },
      { id: "s3", label: "Drafted follow-up email", at: minsFromNow(-88), state: "done" },
      { id: "s4", label: "Waiting for Omar to approve sending", at: minsFromNow(-86), state: "active" },
    ],
    question: null,
    approval: {
      action: "Send an external email to marcus@forewordvc.com with the DIL results summary.",
      reason: "External email sending requires approval in the first version.",
    },
    proof: null,
  },
  {
    id: "run-4",
    taskId: "task-13",
    taskName: "Verify Parakeet ASR latency on M1 Air baseline",
    agent: "Research agent",
    requester: "omar",
    startedAt: minsFromNow(-52),
    runtimeMin: 52,
    tokens: 188_000,
    costUsd: 1.44,
    status: "waiting_input",
    liveStatus: "Needs a decision",
    budgetUsd: 4,
    timeLimitMin: 120,
    steps: [
      { id: "s1", label: "Set up benchmark harness", at: minsFromNow(-50), state: "done" },
      { id: "s2", label: "Ran 40 transcription passes", detail: "P50 0.9s, P95 2.4s on 60s windows", at: minsFromNow(-18), state: "done", raw: "bench.py --windows 40 --model parakeet_mlx" },
      { id: "s3", label: "Question for Omar", at: minsFromNow(-9), state: "active" },
    ],
    question: {
      text: "P95 latency is 2.4s, above the 2.0s target but only on the first window after wake. Should I count cold-start windows in the pass/fail?",
      options: ["Exclude cold-start windows", "Include them — target must hold cold", "Pause and I'll look myself"],
    },
    approval: null,
    proof: null,
  },
  {
    id: "run-5",
    taskId: null,
    taskName: "Competitive sweep — wearable AI pricing changes",
    agent: "Browser agent",
    requester: "omar",
    startedAt: at(16, 10, -1),
    runtimeMin: 22,
    tokens: 240_000,
    costUsd: 1.92,
    status: "done",
    liveStatus: "Done",
    budgetUsd: 3,
    timeLimitMin: 45,
    steps: [
      { id: "s1", label: "Visited 8 competitor sites", at: at(16, 14, -1), state: "done" },
      { id: "s2", label: "Extracted current pricing and ship dates", at: at(16, 24, -1), state: "done" },
      { id: "s3", label: "Compiled comparison table", at: at(16, 30, -1), state: "done" },
      { id: "s4", label: "Verified result", detail: "Spot-checked 3 prices against archive.org", at: at(16, 32, -1), state: "done" },
    ],
    question: null,
    approval: null,
    proof: {
      summary: "Two competitors moved: Plaud cut to $129, Bee AI now bundled with Prime. No one ships an approve-then-act loop.",
      sitesVisited: ["plaud.ai", "bee.computer", "limitless.ai", "meta.com/smart-glasses", "rabbit.tech", "based.tools", "omi.me", "friend.com"],
      screenshots: ["pricing-plaud.png", "pricing-bee.png"],
      tests: "3/3 spot checks matched",
    },
  },
  {
    id: "run-6",
    taskId: null,
    taskName: "Fix flaky pendant BLE reconnect test",
    agent: "Claude Code",
    requester: "jose",
    startedAt: at(11, 0, -1),
    runtimeMin: 61,
    tokens: 520_000,
    costUsd: 4.05,
    status: "failed",
    liveStatus: "Failed — time limit reached",
    budgetUsd: 5,
    timeLimitMin: 60,
    steps: [
      { id: "s1", label: "Read firmware test suite", at: at(11, 5, -1), state: "done" },
      { id: "s2", label: "Reproduced flake 3/20 runs", at: at(11, 30, -1), state: "done" },
      { id: "s3", label: "Attempted fix — timing guard", at: at(11, 50, -1), state: "done" },
      { id: "s4", label: "Time limit reached before verification", at: at(12, 1, -1), state: "done" },
    ],
    question: null,
    approval: null,
    proof: {
      summary: "Not completed. Repro is reliable (3/20). Suggest a human look at the connection supervisor timeout.",
      filesChanged: [],
      tests: "Verification did not run",
    },
  },
];

export const EVENTS: CalendarEvent[] = [
  { id: "e1", title: "Alta Manufacturing — tooling review", start: minsFromNow(47), end: minsFromNow(77), kind: "meeting", attendees: ["jose", "omar"], source: "google" },
  { id: "e2", title: "Engine standup", start: at(13, 0), end: at(13, 15), kind: "meeting", attendees: ["omar", "ari", "jose"], source: "google" },
  { id: "e3", title: "Focus — battery specification", start: at(14, 0), end: at(15, 30), kind: "focus", attendees: ["omar"], source: "hq" },
  { id: "e4", title: "Investor follow-up due (Marcus)", start: at(16, 30), end: at(16, 30), kind: "deadline", source: "hq" },
  { id: "e5", title: "Prep — Alta tooling questions", start: minsFromNow(17), end: minsFromNow(45), kind: "prep", attendees: ["jose"], source: "hq" },
  { id: "e6", title: "Agent deadline — ASR latency verification", start: at(13, 0, 1), end: at(13, 0, 1), kind: "agent", source: "hq" },
  { id: "e7", title: "Pendant wear test check-in", start: at(9, 30, 1), end: at(10, 0, 1), kind: "meeting", attendees: ["jose", "omar"], source: "google" },
  { id: "e8", title: "Follow-up — Alta action items", start: at(9, 0, 1), end: at(9, 15, 1), kind: "followup", attendees: ["jose"], source: "hq" },
  { id: "e9", title: "Weekly clean-room deploy", start: at(11, 0, 4), end: at(12, 0, 4), kind: "deadline", source: "hq" },
  { id: "e10", title: "Product video review", start: at(10, 0, 2), end: at(10, 30, 2), kind: "meeting", attendees: ["omar", "ari"], source: "google" },
];

export const NOTIFICATIONS: HQNotification[] = [
  { id: "n1", kind: "approval", text: "Claude Code needs permission to update the onboarding database", at: minsFromNow(-2), read: false, href: "/hq/agents/run-1" },
  { id: "n2", kind: "approval", text: "Review investor follow-up to Marcus before sending", at: minsFromNow(-86), read: false, href: "/hq/agents/run-3" },
  { id: "n3", kind: "agent_failed", text: "Fix flaky pendant BLE reconnect test — failed at time limit", at: at(12, 1, -1), read: false, href: "/hq/agents/run-6" },
  { id: "n4", kind: "mention", text: "Jose mentioned you on \"Test the pendant microphone\"", at: at(17, 42, -1), read: true, href: "/hq/work" },
  { id: "n5", kind: "due_soon", text: "\"Write the new battery specification\" is due at 14:00", at: minsFromNow(-30), read: false, href: "/hq/work" },
  { id: "n6", kind: "agent_done", text: "Competitive sweep finished — two pricing changes found", at: at(16, 32, -1), read: true, href: "/hq/agents/run-5" },
  { id: "n7", kind: "calendar", text: "Alta Manufacturing tooling review starts soon", at: minsFromNow(-5), read: false, href: "/hq/calendar" },
  { id: "n8", kind: "overdue", text: "\"Follow up with Marcus\" was due earlier — still waiting on approval", at: minsFromNow(-10), read: false, href: "/hq/agents/run-3" },
  { id: "n9", kind: "followup", text: "Follow up on Alta action items tomorrow 09:00", at: at(18, 0, -1), read: true, href: "/hq/calendar" },
];
