export const SOURCE_TRUTH_PATH =
  "/Users/omarebrahim/.codex/attachments/e0e18a4b-bcbb-410a-a9ec-beb1ef328da2/pasted-text.txt";

export const NAV_ITEMS = [
  { href: "/welcome", label: "Welcome" },
  { href: "/sign", label: "Sign" },
  { href: "/setup", label: "Setup" },
  // S3 §3.5: one Onboarding destination so onboarding-2/3/5/7 always highlight
  // here (the active check in PhaseZeroApp maps any onboarding-* screen to this).
  { href: "/onboarding/2", label: "Onboarding" },
  { href: "/", label: "Board" },
  { href: "/settings", label: "Settings" },
];

export const SOURCE_TAGS = [
  "ST-ACTIVE-LISTENING",
  "ST-INFER-REAL-TASKS",
  "ST-IGNORE-VENTS",
  "ST-ACT-PREPARE-ASK-SILENT",
  "ST-BROWSER-REAL-SYSTEMS",
  "ST-MEMORY-COMPOUNDS",
  "ST-TRUST-DIAL",
  "ST-MONEY-IRREVERSIBLE-CONFIRM",
  "ST-LAYERED-ONBOARDING",
  "ST-NO-FAKE-DONE",
  "UX-TEXT-FIRST",
  "OPS-BASIC-PLUMBING",
];

// The map's flow: you (name + phone) → how I work → "can I call you?" → read my world
// (consent + the deep multi-round loop) → the Who-I-Am mirror.
export const ONBOARDING_STAGES = [
  {
    route: "/onboarding/basics",
    label: "Basics",
    title: "Readiness check",
    visible: false,
    status: "read_only",
    copy: "I make sure sign-in, browser helper, voice/text, and engine status are reachable before the deeper setup starts.",
    sourceTags: ["ST-LAYERED-ONBOARDING", "OPS-BASIC-PLUMBING"],
  },
  {
    route: "/onboarding/2",
    label: "You",
    title: "Tell me the obvious things",
    visible: true,
    status: "live",
    copy: "Your name, one sentence about you, your phone, and where I should slow down.",
    sourceTags: ["ST-TRUST-DIAL", "UX-TEXT-FIRST"],
  },
  {
    route: "/onboarding/3",
    label: "How I work",
    title: "How this whole thing works",
    visible: true,
    status: "live",
    copy: "One clean screen: I listen, I catch the real tasks, I ask before acting, I remember.",
    sourceTags: ["ST-LAYERED-ONBOARDING", "UX-TEXT-FIRST"],
  },
  {
    route: "/onboarding/4",
    label: "The call",
    title: "Can I call you?",
    visible: true,
    status: "live",
    copy: "A short call: a few sharp questions, and your say-so before I look through your world.",
    sourceTags: ["ST-LAYERED-ONBOARDING", "ST-TRUST-DIAL"],
  },
  {
    route: "/onboarding/5",
    label: "Your world",
    title: "I read your world — with your say-so",
    visible: true,
    status: "live",
    copy: "You choose what I may read. I go through your signed-in accounts in rounds, deeper each pass, honest about gaps.",
    sourceTags: ["ST-LAYERED-ONBOARDING", "ST-BROWSER-REAL-SYSTEMS", "ST-MEMORY-COMPOUNDS"],
  },
  {
    route: "/onboarding/8",
    label: "Who I am",
    title: "Here is who I think you are",
    visible: true,
    status: "live",
    copy: "Your dossier — your people, your work, your open threads. Fix anything that's wrong; it's corrected everywhere.",
    sourceTags: ["ST-LAYERED-ONBOARDING", "ST-NO-FAKE-DONE"],
  },
];

export const FIXTURES = [
  {
    id: "founder-term-sheet",
    category: "Founder / CEO",
    heard: "We are sending the term sheet tonight. There is a pro-rata side letter and a 20% option pool refresh pre-money.",
    ignored: "I am exhausted, I cannot do another diligence cycle.",
    caught: "Inbound term sheet and flagged dilution terms need review.",
    browserWork: "Watch Gmail thread, find cap table in Drive, compare dilution, draft pushback.",
    checkIn: "The pool being pre-money costs real dilution. Want me to draft the pushback?",
    proof: "Comparison doc prepared; pushback email drafted, not sent.",
    memory: "Founder floor and investor preferences updated.",
    followUp: "Watch for the actual term sheet tonight.",
    risk: "ask",
  },
  {
    id: "lawyer-contract",
    category: "Lawyer",
    heard: "Can you get the revised contract to opposing counsel before Friday?",
    ignored: "This whole matter is making me insane.",
    caught: "Revised contract due before Friday.",
    browserWork: "Open matter folder, find latest draft, compare redlines, prepare email.",
    checkIn: "I have the revised contract ready for review before it goes out.",
    proof: "Draft email prepared with the right attachment; nothing sent.",
    memory: "Matter contact and deadline saved.",
    followUp: "Surface again Thursday if not approved.",
    risk: "ask",
  },
  {
    id: "clinician-consult",
    category: "Clinician",
    heard: "Mr. Okafor's creatinine bumped from 1.1 to 1.9 and renal has not been consulted yet.",
    ignored: "This service has been a mess all week.",
    caught: "Review renal trend and missing consult.",
    browserWork: "Open EMR, read results, prepare consult note or reminder according to allowed workflow.",
    checkIn: "This is clinical and irreversible, so I prepared context and stopped for you.",
    proof: "Patient-specific summary parked; no order placed.",
    memory: "Clinical safety rule reinforced.",
    followUp: "Keep on active work until user resolves.",
    risk: "blocked",
  },
  {
    id: "real-estate-price-drop",
    category: "Real estate",
    heard: "Can we lower the listing before the weekend?",
    ignored: "I am tired of cleaning every time someone wants to peek.",
    caught: "Seller wants a listing price-change decision before weekend.",
    browserWork: "Open listing system, pull showing feedback, comps, and current days-on-market.",
    checkIn: "Price changes affect money, so I built the CMA and stopped.",
    proof: "CMA packet prepared; no listing change made.",
    memory: "Seller urgency and property context saved.",
    followUp: "Ask again Friday morning if no decision.",
    risk: "blocked",
  },
  {
    id: "sales-followup",
    category: "Sales / operator",
    heard: "Can you send the deck and API docs to the partner?",
    ignored: "Everyone says no rush and means tomorrow.",
    caught: "Send current deck and public API docs.",
    browserWork: "Find latest external deck, verify docs link is public, draft follow-up.",
    checkIn: "The deck and docs are ready. Okay to send?",
    proof: "Correct deck and public docs link in draft.",
    memory: "Partner interest in integration saved.",
    followUp: "Watch for reply after two business days.",
    risk: "ask",
  },
  {
    id: "recruiter-final-round",
    category: "Recruiter / talent",
    heard: "Two backend candidates have been sitting in final round for two weeks.",
    ignored: "Or we just never sleep again.",
    caught: "Final-round candidates are stalled and blocking hiring.",
    browserWork: "Open ATS, read scorecards, identify owner and missing step, propose slots.",
    checkIn: "Both blockers are on our side. Want the debrief or offer prep first?",
    proof: "Blockers named; debrief slots proposed; offer terms not sent.",
    memory: "Backend hiring priority saved.",
    followUp: "Escalate if no debrief scheduled in 24 hours.",
    risk: "ask",
  },
  {
    id: "accountant-receipts",
    category: "Accountant / bookkeeper",
    heard: "We still need those two receipts before close.",
    ignored: "I am so done chasing people for paperwork.",
    caught: "Two missing receipts are blocking close.",
    browserWork: "Open bookkeeping system and email, identify transactions and draft chase.",
    checkIn: "The chase is ready. Okay to send it the normal way?",
    proof: "Transactions flagged awaiting receipt; draft chase prepared.",
    memory: "Close dependency tracked.",
    followUp: "Do not mark close done until receipts land.",
    risk: "ask",
  },
  {
    id: "household-return",
    category: "Parent / household",
    heard: "We should send the air fryer back before the return window closes.",
    ignored: "That brand is garbage.",
    caught: "Check return window and prepare return.",
    browserWork: "Open retailer order history, verify purchase date, prepare return path.",
    checkIn: "Return is prepared; I stopped before final submission.",
    proof: "Return page parked with deadline confirmed.",
    memory: "Household return preference saved.",
    followUp: "Nudge before return window closes.",
    risk: "ask",
  },
  {
    id: "employee-report",
    category: "Employee / internal operator",
    heard: "The Friday report needs the new numbers and a note about churn.",
    ignored: "This meeting could have been an email.",
    caught: "Friday report needs refreshed numbers and churn note.",
    browserWork: "Open dashboard, pull numbers, update report draft.",
    checkIn: "Report draft is updated. Want to review the churn wording?",
    proof: "Draft updated; no send or share change.",
    memory: "Weekly reporting cadence saved.",
    followUp: "Surface Friday morning.",
    risk: "do",
  },
  {
    id: "freelancer-newsletter",
    category: "Freelancer / creative",
    heard: "The newsletter should go Thursday; I have a half-written pricing piece in Notion.",
    ignored: "I have basically done fortnightly for a month.",
    caught: "Newsletter slot and draft source.",
    browserWork: "Open Notion, find draft, prepare newsletter outline and send checklist.",
    checkIn: "I found the draft and built the send checklist.",
    proof: "Outline and checklist prepared.",
    memory: "Thursday newsletter routine saved as inferred.",
    followUp: "Nudge Wednesday afternoon if unfinished.",
    risk: "do",
  },
  {
    id: "student-grades",
    category: "Student / researcher",
    heard: "Grades need to be in Gradescope and synced to Canvas by Thursday EOD.",
    ignored: "We cannot be late.",
    caught: "TA grading deadline before regrade requests open.",
    browserWork: "Open Gradescope and Canvas, compare roster/sync state, prepare checklist.",
    checkIn: "The grading checklist is ready; sync is not run without your okay.",
    proof: "Deadline and sync dependency tracked.",
    memory: "Course staff deadline saved.",
    followUp: "Surface Thursday morning.",
    risk: "ask",
  },
];
