#!/usr/bin/env python3
"""Generate src/pb/schema.ts from migration/d1/schema.sql.

schema.ts's own header has said "GENERATED, NOT HAND-WRITTEN" since it was
created, and described `npm run gen:schema`. That script did not exist. The
file was hand-filled for "the four collections the skeleton exercises" and
never finished, which is why evidence, owner_profile, pendants, purges and
segments -- five collections SHIPPED CLIENTS call -- were absent and answered
404 while production answered 200.

The map is the allowlist that decides which identifiers may be concatenated
into SQL (filter-dsl.ts Compiler.column), so drift here is not cosmetic: a
missing column is a 400 on a legitimate client filter, and a missing
collection is a 404 on a route the iPhone depends on.

Which collections are exposed is a DELIBERATE list, not "every table". D1 holds
26 tables; production's guard refuses the internal_* and fellow_* families
through the records API, so exposing them here would be a widening of the
attack surface disguised as a refactor. EXPOSED is that decision, written down.
"""
import re, sys, os

HERE = os.path.dirname(os.path.abspath(__file__))
SQL = os.path.join(HERE, "..", "..", "d1", "schema.sql")
OUT = os.path.join(HERE, "..", "src", "pb", "schema.ts")

# Verified 2026-09-04 by calling /api/collections/<c>/records on BOTH origins
# with the service token: production answers 200 for each of these and 403 for
# every other table. Parity with production is the rule; anything added here
# must be justified by production answering 200.
EXPOSED = ["jobs", "agents", "events", "owners",
           "evidence", "owner_profile", "pendants", "purges", "segments"]

# The seven an account may reach at all — guard.pb.js:416.
ACCOUNT_REACHABLE = ["jobs", "events", "owner_profile", "segments",
                     "agents", "pendants", "evidence"]


def parse_tables(text):
    tables = {}
    for m in re.finditer(r'CREATE TABLE(?:\s+IF NOT EXISTS)?\s+"?([a-z_]+)"?\s*\((.*?)\n\);',
                         text, re.S):
        name, body = m.group(1), m.group(2)
        cols = []
        for line in body.split("\n"):
            cm = re.match(r'\s*"([a-z_A-Z]+)"\s+(TEXT|INTEGER|REAL|NUMERIC|BLOB)', line)
            if not cm:
                continue
            col, sqltype = cm.group(1), cm.group(2)
            comment = line.split("--", 1)[1].strip().lower() if "--" in line else ""
            cols.append((col, sqltype, comment))
        tables[name] = cols
    return tables


def pb_type(table, col, sqltype, comment):
    """SQL type + the column's own comment decide the PocketBase type.

    The comments in schema.sql were written by whoever transcribed the
    collections and they say 'bool', 'number', 'relation->owners' explicitly.
    Using them beats guessing from the SQL type, because INTEGER is both
    `paired` (a bool) and `attempts` (a number)."""
    if col in ("created", "updated") or col.endswith("_at"):
        return "D"
    if "bool" in comment:
        return "B"
    if col.endswith("_ref") or "relation" in comment:
        return "R"
    if sqltype in ("INTEGER", "REAL", "NUMERIC"):
        return "N"
    if col == "email" and table == "owners":
        return '{ type: "email" }'
    return "T"


def main():
    text = open(SQL).read()
    tables = parse_tables(text)
    missing = [t for t in EXPOSED if t not in tables]
    if missing:
        sys.exit("schema.sql has no CREATE TABLE for: %s" % ", ".join(missing))

    out = ['/**',
           ' * src/pb/schema.ts — the compile-time column map.',
           ' *',
           ' * GENERATED BY scripts/gen_schema.py FROM migration/d1/schema.sql. Do not edit',
           ' * by hand; run `npm run gen:schema` instead.',
           ' *',
           ' * WHY IT MUST BE GENERATED: this map is the allowlist that decides which',
           ' * identifiers may be concatenated into SQL (filter-dsl.ts `Compiler.column`).',
           ' * A hand-maintained copy that drifts from schema.sql produces a 400 on a',
           ' * legitimate client filter — which reads to the customer as "Anticipy is',
           ' * down" — and a missing COLLECTION produces a 404 on a route a shipped',
           ' * client depends on. Both happened: this file claimed to be generated for',
           ' * weeks while no generator existed, and five collections the iPhone, the',
           ' * extension and brain/ all call were simply absent.',
           ' */',
           'import type { CollectionSchema } from "../../filter-dsl.ts";',
           '',
           'export interface CollectionDef {',
           '  name: string;',
           '  columns: CollectionSchema;',
           '  /** Columns that are INTEGER 0/1 in D1 and booleans on the wire. */',
           '  boolColumns: readonly string[];',
           '  /**',
           '   * Columns PocketBase would have filled itself. In D1 there is no autodate;',
           '   * the Worker fills them. migration/d1/schema.sql, `autodate` in the type map.',
           '   */',
           '  createdColumn?: string;',
           '  updatedColumn?: string;',
           '}',
           '',
           'const T = { type: "text" } as const;',
           'const D = { type: "date" } as const;',
           'const R = { type: "relation" } as const;',
           'const N = { type: "number" } as const;',
           'const B = { type: "bool" } as const;',
           '',
           'export const COLLECTIONS: Readonly<Record<string, CollectionDef>> = {']

    for t in EXPOSED:
        cols = tables[t]
        bools = [c for c, st, cm in cols if pb_type(t, c, st, cm) == "B"]
        has_created = any(c == "created" for c, _, _ in cols)
        has_updated = any(c == "updated" for c, _, _ in cols)
        out.append('  %s: {' % t)
        out.append('    name: "%s",' % t)
        out.append('    columns: {')
        line = '      '
        for c, st, cm in cols:
            piece = '%s: %s, ' % (c, pb_type(t, c, st, cm))
            if len(line) + len(piece) > 96:
                out.append(line.rstrip()); line = '      '
            line += piece
        if line.strip():
            out.append(line.rstrip().rstrip(','))
        out.append('    },')
        out.append('    boolColumns: [%s],' % ", ".join('"%s"' % b for b in bools))
        if has_created or has_updated:
            bits = []
            if has_created: bits.append('createdColumn: "created"')
            if has_updated: bits.append('updatedColumn: "updated"')
            out.append('    %s,' % ", ".join(bits))
        out.append('  },')
    out.append('};')
    out.append('')
    out.append('/**')
    out.append(' * The collections a signed-in account may reach AT ALL.')
    out.append(' * guard.pb.js:416 — the regex is the allowlist, and anything else is')
    out.append(' * `403 {"error":"account is not allowed to access that collection"}`.')
    out.append(' */')
    out.append('export const ACCOUNT_REACHABLE = [')
    out.append('  %s,' % ", ".join('"%s"' % a for a in ACCOUNT_REACHABLE))
    out.append('] as const;')

    tail = open(OUT).read()
    idx = tail.find("/**\n * Sort keys a caller may name.")
    if idx < 0:
        sys.exit("could not find the parseSort block to preserve")
    out.append('')
    out.append(tail[idx:].rstrip("\n"))
    open(OUT, "w").write("\n".join(out) + "\n")
    print("  generated %s: %d collections" % (os.path.relpath(OUT), len(EXPOSED)))
    for t in EXPOSED:
        print("    %-16s %2d columns" % (t, len(tables[t])))


main()
