import * as React from "react";

/**
 * Anticipy transactional receipt template.
 *
 * Plain React + inline styles. Intentionally avoids @react-email/components
 * so the build never gates on that dependency. At runtime the Resend SDK
 * still calls @react-email/render to turn this tree into email-safe HTML,
 * and any plain React element works there.
 *
 * Apple-feel rules (locked):
 *   no em-dashes (use periods, commas, parens)
 *   plain words (no jargon, no salesy adjectives)
 *   single dark CTA, generous whitespace, system fonts
 *   brand colors only: dark (#0C0C0C), cream (#F5F0EB), gold (#C8A97E)
 *
 * The Resend broker route (/api/email/receipt) constructs this element
 * and passes it to sendEmail(). Auto plain-text is generated by Resend
 * unless we override.
 */

export interface ReceiptProps {
  recipientName?: string;
  goalSummary: string;
  actionTaken: string;
  nextSteps?: string;
}

const FONT_STACK =
  "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Segoe UI', Helvetica, Arial, sans-serif";

const SERIF_STACK = "Georgia, 'Times New Roman', serif";

const styles: Record<string, React.CSSProperties> = {
  body: {
    margin: 0,
    padding: 0,
    backgroundColor: "#0C0C0C",
    color: "#FAFAFA",
    fontFamily: FONT_STACK,
  },
  wrapper: {
    width: "100%",
    backgroundColor: "#0C0C0C",
    padding: "32px 16px",
  },
  card: {
    maxWidth: 520,
    margin: "0 auto",
    backgroundColor: "#111111",
    border: "1px solid #1F1F1F",
    borderRadius: 16,
    padding: "28px 32px",
  },
  brand: {
    fontFamily: SERIF_STACK,
    fontSize: 20,
    letterSpacing: "0.02em",
    color: "#C8A97E",
    margin: 0,
  },
  kicker: {
    marginTop: 22,
    fontSize: 13,
    color: "#8A8A8A",
    lineHeight: 1.4,
  },
  summary: {
    marginTop: 8,
    fontSize: 17,
    lineHeight: 1.45,
    color: "#FAFAFA",
    fontWeight: 600,
  },
  sectionLabel: {
    marginTop: 22,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    color: "#8A8A8A",
  },
  paragraph: {
    marginTop: 8,
    fontSize: 15,
    lineHeight: 1.6,
    color: "#E8E8E8",
  },
  divider: {
    marginTop: 24,
    border: 0,
    borderTop: "1px solid #1F1F1F",
  },
  footer: {
    marginTop: 18,
    fontSize: 12,
    lineHeight: 1.5,
    color: "#5A5A5A",
  },
  preheader: {
    display: "none",
    fontSize: 1,
    lineHeight: "1px",
    maxHeight: 0,
    maxWidth: 0,
    opacity: 0,
    overflow: "hidden",
    color: "#0C0C0C",
  },
};

function buildPreheader(summary: string): string {
  const trimmed = summary.trim();
  if (trimmed.length <= 120) return trimmed;
  return `${trimmed.slice(0, 117)}...`;
}

export function Receipt(props: ReceiptProps): React.ReactElement {
  const { recipientName, goalSummary, actionTaken, nextSteps } = props;
  const greeting = recipientName?.trim()
    ? `Hi ${recipientName.trim()},`
    : "Hi,";

  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="color-scheme" content="dark light" />
        <meta name="supported-color-schemes" content="dark light" />
        <title>Anticipy</title>
      </head>
      <body style={styles.body}>
        <div style={styles.preheader}>{buildPreheader(goalSummary)}</div>
        <div style={styles.wrapper}>
          <div style={styles.card}>
            <p style={styles.brand}>Anticipy</p>

            <p style={styles.kicker}>{greeting}</p>
            <p style={styles.summary}>{goalSummary}</p>

            <p style={styles.sectionLabel}>What I did</p>
            <p style={styles.paragraph}>{actionTaken}</p>

            {nextSteps ? (
              <>
                <p style={styles.sectionLabel}>What is next</p>
                <p style={styles.paragraph}>{nextSteps}</p>
              </>
            ) : null}

            <hr style={styles.divider} />
            <p style={styles.footer}>
              Reply to this email and Anticipy will pick up the thread.
            </p>
          </div>
        </div>
      </body>
    </html>
  );
}

export default Receipt;
