/**
 * src/pb/schema.ts — the compile-time column map.
 *
 * GENERATED BY scripts/gen_schema.py FROM migration/d1/schema.sql. Do not edit
 * by hand; run `npm run gen:schema` instead.
 *
 * WHY IT MUST BE GENERATED: this map is the allowlist that decides which
 * identifiers may be concatenated into SQL (filter-dsl.ts `Compiler.column`).
 * A hand-maintained copy that drifts from schema.sql produces a 400 on a
 * legitimate client filter — which reads to the customer as "Anticipy is
 * down" — and a missing COLLECTION produces a 404 on a route a shipped
 * client depends on. Both happened: this file claimed to be generated for
 * weeks while no generator existed, and five collections the iPhone, the
 * extension and brain/ all call were simply absent.
 */
import type { CollectionSchema } from "../../filter-dsl.ts";

export interface CollectionDef {
  name: string;
  columns: CollectionSchema;
  /** Columns that are INTEGER 0/1 in D1 and booleans on the wire. */
  boolColumns: readonly string[];
  /**
   * Columns PocketBase would have filled itself. In D1 there is no autodate;
   * the Worker fills them. migration/d1/schema.sql, `autodate` in the type map.
   */
  createdColumn?: string;
  updatedColumn?: string;
}

const T = { type: "text" } as const;
const D = { type: "date" } as const;
const R = { type: "relation" } as const;
const N = { type: "number" } as const;
const B = { type: "bool" } as const;

export const COLLECTIONS: Readonly<Record<string, CollectionDef>> = {
  jobs: {
    name: "jobs",
    columns: {
      id: T, created: D, updated: D, goal: T, params: T, status: T, result: T, device_id: T,
      owner: T, claimed_by: T, claimed_at: D, owner_ref: R, lane: T, attempts: N, trace: T,
      workflow_id: T, workflow_version: N, workflow_state: T, consequence: T, lineage_key: T,
      effect_key: T, scope_digest: T, approval: T, receipt: T, reconciliation: T,
      lease_token: T, lease_until: T, source_event_ids: T, effect_uncertain: B,
      watching_until: T, commitment_key: T
    },
    boolColumns: ["effect_uncertain"],
    createdColumn: "created", updatedColumn: "updated",
  },
  agents: {
    name: "agents",
    columns: {
      id: T, created: D, updated: D, agent_id: T, pair_code: T, owner: T, paired: B,
      last_seen: T, browser: T, owner_ref: R, agent_token: T, llm_calls: N, llm_hour: T,
      solve_calls: N, solve_hour: T
    },
    boolColumns: ["paired"],
    createdColumn: "created", updatedColumn: "updated",
  },
  events: {
    name: "events",
    columns: {
      id: T, created: D, updated: D, device_id: T, kind: T, text: T, decision: T, goal: T,
      needs_confirmation: B, capture_started_at: D, capture_ended_at: D, gap_before_ms: N,
      seq: N, boot_id: T, source: T, backfill: B, segment: R, speaker: T, owner_ref: R,
      addressee: T, spoken_at: D, parent_line: T, external_event_id: T, explicit: B,
      importance: N, heard_ms: N, heard_calls: N
    },
    boolColumns: ["needs_confirmation", "backfill", "explicit"],
    createdColumn: "created", updatedColumn: "updated",
  },
  owners: {
    name: "owners",
    columns: {
      id: T, created: D, updated: D, email: { type: "email" }, emailVisibility: B, verified: B,
      password: T, tokenKey: T, phone: T, legacy_uuid: T
    },
    boolColumns: ["emailVisibility", "verified"],
    createdColumn: "created", updatedColumn: "updated",
  },
  evidence: {
    name: "evidence",
    columns: {
      id: T, created: D, updated: D, owner_ref: R, job: R, effect_key: T, image: T,
      share_expires: T, fetches: N
    },
    boolColumns: [],
    createdColumn: "created", updatedColumn: "updated",
  },
  owner_profile: {
    name: "owner_profile",
    columns: {
      id: T, created: D, updated: D, owner_id: T, phone: T, name: T, first_name: T,
      last_name: T, email: T, birthday: T, facts: T, owner_ref: R, timezone: T
    },
    boolColumns: [],
    createdColumn: "created", updatedColumn: "updated",
  },
  pendants: {
    name: "pendants",
    columns: {
      id: T, created: D, updated: D, device_id: T, name: T, pair_code: T, owner: T, paired: B,
      battery: N, owner_ref: R
    },
    boolColumns: ["paired"],
    createdColumn: "created", updatedColumn: "updated",
  },
  purges: {
    name: "purges",
    columns: {
      id: T, created: D, updated: D, owner_ref: R, legacy_uuid: T, memory_purged: B,
      requested_at: D, purged_at: D
    },
    boolColumns: ["memory_purged"],
    createdColumn: "created", updatedColumn: "updated",
  },
  segments: {
    name: "segments",
    columns: {
      id: T, created: D, updated: D, owner: T, status: T, started_at: D, last_speech_at: D,
      ended_at: D, turn_count: N, word_count: N, summary: T, entities: T, parent_segment: T,
      triaged_through_seq: N, dirty: B, supersedes: T, owner_ref: R
    },
    boolColumns: ["dirty"],
    createdColumn: "created", updatedColumn: "updated",
  },
};

/**
 * The collections a signed-in account may reach AT ALL.
 * guard.pb.js:416 — the regex is the allowlist, and anything else is
 * `403 {"error":"account is not allowed to access that collection"}`.
 */
export const ACCOUNT_REACHABLE = [
  "jobs", "events", "owner_profile", "segments", "agents", "pendants", "evidence",
] as const;

/**
 * Sort keys a caller may name. Same boundary as the filter identifiers: a
 * `sort` parameter is concatenated into an ORDER BY, so it is validated
 * against the column map and nothing else may pass.
 */
export function parseSort(spec: string, def: CollectionDef): { sql: string } {
  if (!spec) return { sql: "" };
  const parts: string[] = [];
  for (const raw of spec.split(",")) {
    const term = raw.trim();
    if (!term) continue;
    let dir = "ASC";
    let name = term;
    if (term.startsWith("-")) { dir = "DESC"; name = term.slice(1); }
    else if (term.startsWith("+")) { name = term.slice(1); }
    // PocketBase supports @random. Nothing in this tree sends it; refuse.
    if (!Object.prototype.hasOwnProperty.call(def.columns, name)) {
      throw new Error(`unknown sort field ${JSON.stringify(name)}`);
    }
    parts.push(`"${name.replace(/"/g, '""')}" ${dir}`);
  }
  return { sql: parts.length ? ` ORDER BY ${parts.join(", ")}` : "" };
}
