#!/usr/bin/env bash
#
# Anticipy v4 installer — macOS.
#
# What it does (in order):
#   1. Verifies Python 3.10+ is available.
#   2. Creates ~/.anticipy/ with a virtualenv and pip-installs deps.
#   3. Copies anticipy_agent.py + protocol.py + native_bridge.py + engine/
#      into ~/.anticipy/.
#   4. Writes a launcher script /usr/local/bin/anticipy-agent that
#      activates the venv and runs the daemon.
#   5. Drops com.anticipy.agent.json into the NativeMessagingHosts dir
#      with __EXTENSION_ID__ replaced by the v4 pinned ID.
#   6. Prints next steps for loading the unpacked extension.
#
# Linux / Windows paths noted but NOT implemented. PRs welcome.

set -euo pipefail

# Pinned v4 extension ID. Derived from the RSA public key in
# extension_v4/manifest.json — DO NOT change without regenerating the key.
EXTENSION_ID="npnpagopediecennpleihemoochikggb"

ANTICIPY_HOME="${HOME}/.anticipy"
VENV_DIR="${ANTICIPY_HOME}/venv"
LAUNCHER="/usr/local/bin/anticipy-agent"
NM_DIR="${HOME}/Library/Application Support/Google/Chrome/NativeMessagingHosts"

# When installed from the zipped bundle, this script lives at
# bundle_root/installer/install.sh; native_host/ is its sibling.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUNDLE_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
NATIVE_HOST_SRC="${BUNDLE_ROOT}/native_host"
ENGINE_SRC="${BUNDLE_ROOT}/engine"

step() { printf "\033[1;36m==>\033[0m %s\n" "$*"; }
warn() { printf "\033[1;33m!! \033[0m %s\n" "$*" >&2; }
die()  { printf "\033[1;31m!! \033[0m %s\n" "$*" >&2; exit 1; }

# 0. Sanity ───────────────────────────────────────────────────────────────

case "$(uname -s)" in
  Darwin) ;;
  *) die "This installer supports macOS only. Linux/Windows: see README.md.";;
esac

if [ ! -d "${NATIVE_HOST_SRC}" ]; then
  die "Missing native_host/ next to installer/. Did you unzip the full bundle?"
fi

# 1. Python ───────────────────────────────────────────────────────────────

PY="$(command -v python3 || true)"
if [ -z "${PY}" ]; then
  die "Python 3.10+ not found. Install from https://www.python.org/downloads/ then re-run."
fi
PYV="$(${PY} -c 'import sys; print("%d.%d" % sys.version_info[:2])')"
PYMAJ="${PYV%%.*}"
PYMIN="${PYV##*.}"
if [ "${PYMAJ}" -lt 3 ] || { [ "${PYMAJ}" -eq 3 ] && [ "${PYMIN}" -lt 10 ]; }; then
  die "Python 3.10+ required (found ${PYV}). Install from python.org and re-run."
fi
step "Using Python ${PYV} at ${PY}"

# 2. Home + venv ──────────────────────────────────────────────────────────

step "Creating ${ANTICIPY_HOME}"
mkdir -p "${ANTICIPY_HOME}"

if [ ! -d "${VENV_DIR}" ]; then
  step "Creating venv"
  "${PY}" -m venv "${VENV_DIR}"
fi

# shellcheck source=/dev/null
source "${VENV_DIR}/bin/activate"
python -m pip install --upgrade pip >/dev/null

# Minimal deps — no patchright, no browser-use. The daemon doesn't drive
# a browser; the extension does.  cryptography is needed by engine.app.config.
step "Installing Python dependencies"
pip install --quiet \
  "httpx>=0.25" \
  "cryptography>=41" \
  "supabase>=2.0" \
  "python-dotenv>=1.0"

# 3. Copy daemon files ────────────────────────────────────────────────────

step "Copying daemon files"
cp "${NATIVE_HOST_SRC}/anticipy_agent.py"  "${ANTICIPY_HOME}/anticipy_agent.py"
cp "${NATIVE_HOST_SRC}/protocol.py"        "${ANTICIPY_HOME}/protocol.py"
cp "${NATIVE_HOST_SRC}/native_bridge.py"   "${ANTICIPY_HOME}/native_bridge.py"
cp "${NATIVE_HOST_SRC}/__init__.py"        "${ANTICIPY_HOME}/__init__.py"
chmod +x "${ANTICIPY_HOME}/anticipy_agent.py"

if [ -d "${ENGINE_SRC}" ]; then
  step "Copying engine modules"
  rm -rf "${ANTICIPY_HOME}/engine"
  cp -R  "${ENGINE_SRC}" "${ANTICIPY_HOME}/engine"
else
  warn "engine/ not in bundle — daemon will fail until you also place it at ${ANTICIPY_HOME}/engine"
fi

# 4. Launcher ─────────────────────────────────────────────────────────────

step "Writing launcher at ${LAUNCHER}"
TMP_LAUNCHER="$(mktemp)"
cat > "${TMP_LAUNCHER}" <<EOF
#!/usr/bin/env bash
# Anticipy agent launcher — generated by install.sh.
# Activates the venv so anticipy_agent.py imports cleanly, then execs it.
# stdio is piped directly to/from Chrome (do NOT print anything else!).
export PYTHONUNBUFFERED=1
exec "${VENV_DIR}/bin/python" "${ANTICIPY_HOME}/anticipy_agent.py"
EOF
chmod +x "${TMP_LAUNCHER}"

if [ -w "$(dirname "${LAUNCHER}")" ] 2>/dev/null; then
  mv "${TMP_LAUNCHER}" "${LAUNCHER}"
else
  step "Need sudo to install launcher at ${LAUNCHER}"
  sudo mv "${TMP_LAUNCHER}" "${LAUNCHER}"
fi
[ -x "${LAUNCHER}" ] || die "Launcher not executable: ${LAUNCHER}"

# 5. Native messaging manifest ────────────────────────────────────────────

step "Installing native messaging manifest"
mkdir -p "${NM_DIR}"
cp "${NATIVE_HOST_SRC}/com.anticipy.agent.json" "${NM_DIR}/com.anticipy.agent.json"
# Replace __EXTENSION_ID__ placeholder with the real ID.
# macOS sed needs the -i '' form.
sed -i '' "s/__EXTENSION_ID__/${EXTENSION_ID}/g" "${NM_DIR}/com.anticipy.agent.json"

step "Manifest written to ${NM_DIR}/com.anticipy.agent.json"

# 6. Done ────────────────────────────────────────────────────────────────

cat <<EOF

================================================================
 Anticipy v4 installed.

 Next steps:
   1. Open chrome://extensions
   2. Toggle "Developer mode" (top-right)
   3. Click "Load unpacked"
   4. Pick the extension_v4/ folder from the bundle:
        ${BUNDLE_ROOT}/extension_v4

   The extension ID should appear as:
        ${EXTENSION_ID}

   (If you see a different ID, the pinned key was modified — the
    native-messaging manifest will refuse to launch the daemon.)

 Logs:  tail -f ~/Library/Logs/Anticipy/agent.log
================================================================
EOF
